"""Generate frontend/lib/events.ts from agent/events.py so the contract cannot drift."""

from __future__ import annotations

import re
from pathlib import Path

SRC = Path("src/mehullm/agent/events.py")
OUT = Path("frontend/lib/events.ts")


def main() -> int:
    block = re.search(r"EventType = Literal\[(.*?)\]", SRC.read_text(encoding="utf-8"), re.S)
    if not block:
        raise SystemExit("EventType literal not found")
    names = re.findall(r'"([a-z_]+)"', block.group(1))
    quoted = ", ".join('"' + n + '"' for n in names)

    lines = [
        "// GENERATED by scripts/gen_events_ts.py -- do not edit.",
        "// Source: src/mehullm/agent/events.py",
        "",
        "export type EventType =",
        *['  | "' + n + '"' for n in names],
        "  ;",
        "",
        "export interface AgentEvent {",
        "  type: EventType;",
        "  seq: number;",
        "  run_id: string;",
        "  trace_id: string;",
        "  ts: number;",
        "  [key: string]: unknown;",
        "}",
        "",
        "export const EVENT_TYPES: EventType[] = [" + quoted + "];",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"{OUT}: {len(names)} event types")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
