// GENERATED by scripts/gen_events_ts.py -- do not edit.
// Source: src/mehullm/agent/events.py

export type EventType =
  | "run_start"
  | "status"
  | "text_delta"
  | "tool_start"
  | "confirmation_request"
  | "confirmation_resolved"
  | "tool_result"
  | "guardrail_blocked"
  | "provider_switch"
  | "voice_start"
  | "voice_delta"
  | "voice_end"
  | "usage"
  | "error"
  | "done"
  ;

export interface AgentEvent {
  type: EventType;
  seq: number;
  run_id: string;
  trace_id: string;
  ts: number;
  [key: string]: unknown;
}

export const EVENT_TYPES: EventType[] = ["run_start", "status", "text_delta", "tool_start", "confirmation_request", "confirmation_resolved", "tool_result", "guardrail_blocked", "provider_switch", "voice_start", "voice_delta", "voice_end", "usage", "error", "done"];
